package com.siloam.healthcare.consulta;

public enum ClassificacaoRisco {
    Vermelha,
    Amarela,
    Verde1,
    Verde2
}

/*
0. PRIORIDADE ZERO (vERMELHA)
ENCAMINHAR DIRETAMENTE PARA A SALA DE RESSUSCITAÇÃO E AvISAR A EQUIPE MÉDICA, ACIONAMENTO DE SINAL SONORO.
NÃO PERDER TEMPO COM CLASSIFICAÇÃO. ATENDIMENTO EM 15 MINUTOS.
EM MORTE IMINENTE.
(EXEMPLO: PARADA CARDIORRESPIRATÓRIA, INFARTO, POLITRAUMA, CHOQUE HIPOvOLêMICO, ETC.)

1. PRIORIDADE I (AMARELA)
ENCAMINHAR PARA CONSULTA MÉDICA IMEDIATA;
URGêNCIA, AvALIAÇÃO EM, NO MáXIMO, 30 MINUTOS.
ELEvADO RISCO DE MORTE.
(EXEMPLO: TRAUMA MODERADO OU LEvE, TCE SEM PERDA DA CONSCIêNCIA, QUEIMADURAS MENORES, DISPNÉIA LEvE A MODERADA, DOR ABDOMINAL, CONvULSÃO, CEFALÉIAS, IDOSOS E GRávIDAS SINTOMáTICOS, ETC.)

2. PRIORIDADE II (vERDE)
ENCAMINHAR PARA CONSULTA MÉDICA, URGêNCIA MENOR.
AvALIAÇÃO EM, NO MáXIMO, 1 HORA. REAvALIAR PERIODICAMENTE.
SEM RISCO DE MORTE.
(EXEMPLO: FERIMENTO CRANIANO MENOR, DOR ABDOMINAL DIFUSA, CEFALÉIA MENOR, DOENÇA PSIQUIáTRICA, DIARRÉIAS, IDOSOS E GRávIDAS ASSINTOMáTICOS, ETC.)

2. PRIORIDADE II (vERDE)
ENCAMINHAR PARA CONSULTA MÉDICA, URGêNCIA MENOR.
AvALIAÇÃO EM, NO MáXIMO, 1 HORA. REAvALIAR PERIODICAMENTE.
SEM RISCO DE MORTE.
(EXEMPLO: FERIMENTO CRANIANO MENOR, DOR ABDOMINAL DIFUSA, CEFALÉIA MENOR, DOENÇA PSIQUIáTRICA, DIARRÉIAS, IDOSOS E GRávIDAS ASSINTOMáTICOS, ETC.)
    */
